### PR TITLE
Addition of Source Specific Station Term (SSST) earthquake relocation algorithm.

### PR DESCRIPTION
**Pull request by Lachlan-Adams**
This adds a SSST relocation algorithm to hiperseis in /hiperseis/seismic/ssst_relocation/, designed to incorporate 3D heterogeneity into travel time prediction. This algorithm works in a similar way to /hiperseis/iloc_rstt/iloc_phase_ident.py.

### CODE REVIEW

**Comment by geojunky** [comment]
Thanks for the pull request @Lachlan-Adams. The spherical geodesic inversion you've added for the coverage plots is great and highly efficient as well. But I was wondering if a simple heat map as implemented in cells 5 and 6 [here](https://github.com/GeoscienceAustralia/hiperseis/blob/develop/seismic/pick_harvester/notebooks/diagnostics_after_iloc_cartopy.ipynb) is more appropriate.

**Comment by geojunky** [comment]
I was wondering if using haversine is a better option [here](https://github.com/GeoscienceAustralia/hiperseis/blob/d6fe733960ada2e011d2d35d4fe7179d78669ded/seismic/ssst_relocation/relocation/relocation_helper.f#L196) than using the method based on the law of cosines.

**Comment by Lachlan-Adams** [comment]
@rh-downunder I have added the heat plot and changed the angular distance calculation in relocation_helper.f to the haversine formula, as you suggested.

**Comment by geojunky** [comment]
Thanks for making the changes.
dtdh is computed [here](https://github.com/GeoscienceAustralia/hiperseis/blob/d6fe733960ada2e011d2d35d4fe7179d78669ded/seismic/ssst_relocation/relocation/tt_table_calculator.py#L234) but I'm not sure it is being used anywhere in the code. The fortran relocation routine seems to only use dtdd.

**Comment by Lachlan-Adams** [comment]
> Thanks for making the changes. dtdh is computed [here](https://github.com/GeoscienceAustralia/hiperseis/blob/d6fe733960ada2e011d2d35d4fe7179d78669ded/seismic/ssst_relocation/relocation/tt_table_calculator.py#L234) but I'm not sure it is being used anywhere in the code. The fortran relocation routine seems to only use dtdd.

Yes that's correct. The iLoc algorithm uses bounce point time corrections based on the horizontal derivative of the travel time table for waves which are reflected at least once between the source and receiver. The fortran relocation routine doesn't currently use any reflected waves but I kept the code in to compute dtdh anyway, in case the capability is to be added in the future. It takes <10 seconds to compute dtdh for all travel time tables, and the memory usage to store dtdh is small.

**Review by geojunky — APPROVED** [review]
Thank you for making the changes.

**Comment by geojunky** [comment]
Please go ahead and merge with develop. I'll try to run the codes and report any issues I may encounter.

**Pull request merged**
