### PR TITLE
Andrew medlin/data integration ws jun2019

### PR DESCRIPTION
**Pull request by medlin01GA**
Variety of changes and improvements made for work related to data integration workshop at GA this week. Most significant are changes to `prepare_rf_data.py` for speeding up the extraction of traces from ASDF database for a set of events. Some changes for Py3 compatibility. Fixed for unconditional exception catching which prevents process from being interrupted with ctrl-C.

### CODE REVIEW

**Comment by rh-downunder** [comment]
Andrew, I'm not sure about the effects of lines 302, 303 in `FederatedASDFDataSetDBVariant.py`. The idea behind `get_waveforms()` is to work off of values (net, sta, loc, cha, lon, lat) returned by `get_stations`. I would revert these changes, especially when we have no tests in place to assess the effects properly. I will add tests to the FederatedASDFDataSet classes soon.

**Comment by medlin01GA** [comment]
> 
> 
> Andrew, I'm not sure about the effects of lines 302, 303 in `FederatedASDFDataSetDBVariant.py`. The idea behind `get_waveforms()` is to work off of values (net, sta, loc, cha, lon, lat) returned by `get_stations`. I would revert these changes, especially when we have no tests in place to assess the effects properly. I will add tests to the FederatedASDFDataSet classes soon.

Unfortunately this change cannot be separated from the changes in `prepare_rf_data.py` lines 51-59. The reason it was required is that the rf library replaces the last letter of the channel code with '?', so for example 'HHZ'-->'HH?' inside rf library before it is passed as an argument into the `custom_get_waveforms` function. This was resulting in the query to the db returning no result since it was performing exact matching.

Would it be acceptable to change the code here to use exact matching like before if there is no '?' in the channel code, but use the new 'like' matching if the channel code has a '?' character?

**Comment by rh-downunder** [comment]
I would do something like this in `custom_get_waveforms()`:
```
matching_stations = asdf_dataset.get_stations(starttime, endtime, network=net, station=sta, location=loc)

for net, sta, loc, cha, _, _ in matching_stations:
    if rf_cha matches cha:
        matching_stream += asdf_dataset.get_waveforms(network, station, location, channel, starttime, endtime)
```
Then iterate over `matching_stations`, compare channel codes to that passed from `rf` and only get those waveforms. In other words, handle this `rf` peculiarity outside of FederatedASDF. Please revert those two lines in FederatedASDF.

**Comment by medlin01GA** [comment]
@rh-downunder I have reverted the query expression in `FederatedASDFDataSetDBVariant` as requested and moved the matching of channel code up into `prepare_rf_data.py`.

**Comment by rh-downunder** [comment]
@medlin01GA thanks; merging now

**Comment by medlin01GA** [comment]
Thanks.

**Pull request merged**
