### PR TITLE
Andrew medlin/pst 398 h k stacking

### PR DESCRIPTION
**Pull request by medlin01GA**
PR for receiver_fn workflow improvements. Note that some aspects of the code are experimental here, such as the various additional waveform statistics added to the trace metadata. Ignore the files under subfolder `c_sippl_reference`, as this is reference code that will be later deleted once the RF processing code has stabilized. We have permission from Christian Sippl for this code to appear in the hiperseis repo.

Please so not merge the pull request after finishing review. I would like to select the merge type myself.

### CODE REVIEW

**Comment by rh-downunder** [comment]
It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.

**Comment by rh-downunder** [comment]
In hindsight, I think it would have been better to host Sipple's code in a separate repo and to use it as a submodule, if the idea from the outset was to remove this code down the road. It helps keep the history of the core repo cleaner.

**Comment by medlin01GA** [comment]
> 
> 
> It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.

I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?

**Comment by rh-downunder** [comment]
> > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> 
> I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?

On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.

**Comment by medlin01GA** [comment]
> 
> 
> > > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> > 
> > 
> > I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?
> 
> On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.

I realize that much, but I'm saying this change seems to have come from develop after commit 477a890791c120887596837129801a04a384a7dd of this branch. I.e, I did an merge from develop, and noticed my `libmseed` and `PhasePApy` folders where in modified state after that merge, as a result of that merge from develop. Does this not mean the change to the submodule versions came from develop?

**Comment by rh-downunder** [comment]
> > > > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> > > 
> > > 
> > > I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?
> > 
> > 
> > On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.
> 
> I realize that much, but I'm saying this change seems to have come from develop after commit [477a890](https://github.com/GeoscienceAustralia/hiperseis/commit/477a890791c120887596837129801a04a384a7dd) of this branch. I.e, I did an merge from develop, and noticed my `libmseed` and `PhasePApy` folders where in modified state after that merge, as a result of that merge from develop. Does this not mean the change to the submodule versions came from develop?

`libmseed` on `develop` still points to `c23cc3d` (October 2017). On this PR it somehow started pointing to `67f0bee` (June 2019). I'm not sure how this change could originate from `develop`.

**Comment by medlin01GA** [comment]
> 
> 
> > > > > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> > > > 
> > > > 
> > > > I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?
> > > 
> > > 
> > > On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.
> > 
> > 
> > I realize that much, but I'm saying this change seems to have come from develop after commit [477a890](https://github.com/GeoscienceAustralia/hiperseis/commit/477a890791c120887596837129801a04a384a7dd) of this branch. I.e, I did an merge from develop, and noticed my `libmseed` and `PhasePApy` folders where in modified state after that merge, as a result of that merge from develop. Does this not mean the change to the submodule versions came from develop?
> 
> `libmseed` on `develop` still points to `c23cc3d` (October 2017). On this PR it somehow started pointing to `67f0bee` (June 2019). I'm not sure how this change could originate from `develop`.

Seems like a submodule can become weirdly detached after pull or merge, such as https://stackoverflow.com/a/36375256/5823205.  I'll try to debug and roll back.

**Comment by rh-downunder** [comment]
> > > > > > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> > > > > 
> > > > > 
> > > > > I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?
> > > > 
> > > > 
> > > > On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.
> > > 
> > > 
> > > I realize that much, but I'm saying this change seems to have come from develop after commit [477a890](https://github.com/GeoscienceAustralia/hiperseis/commit/477a890791c120887596837129801a04a384a7dd) of this branch. I.e, I did an merge from develop, and noticed my `libmseed` and `PhasePApy` folders where in modified state after that merge, as a result of that merge from develop. Does this not mean the change to the submodule versions came from develop?
> > 
> > 
> > `libmseed` on `develop` still points to `c23cc3d` (October 2017). On this PR it somehow started pointing to `67f0bee` (June 2019). I'm not sure how this change could originate from `develop`.
> 
> Seems like a submodule can become weirdly detached after pull or merge, such as https://stackoverflow.com/a/36375256/5823205. I'll try to debug and roll back.

While we're at it, I just wanted to mention that it's happened before in another PR you merged some time ago, which updated the phasepapy submodule. I then had to go through the code to make sure nothing broke. Please keep an eye out to make sure submodules don't get inadvertently updated.
I think something weird is happening in your dev environment; fortunately, I haven't experienced this in mine.

**Comment by medlin01GA** [comment]
> 
> 
> > > > > > > It looks like you've updated the libmseed module. I'm not sure if this will break code (e.g. due to potential api changes) that uses this submodule; unfortunately there are no tests implemented yet for those codes. Please revert back to the version that the hiperseis:develop branch is using. In general, it's not a bad idea not to update any submodules without looking into the ramifications closely.
> > > > > > 
> > > > > > 
> > > > > > I don't remember changing libmseed, and I can't find anything in the log (using `git log --name-status`) indicating I have changed it, other than when I sync'd to changes from the develop branch. Can you give some clear picture of what you think has changed?
> > > > > 
> > > > > 
> > > > > On this PR branch libmseed point to `libmseed @ 67f0bee`, but on develop, libmseed points to `libmseed @ c23cc3d`.
> > > > 
> > > > 
> > > > I realize that much, but I'm saying this change seems to have come from develop after commit [477a890](https://github.com/GeoscienceAustralia/hiperseis/commit/477a890791c120887596837129801a04a384a7dd) of this branch. I.e, I did an merge from develop, and noticed my `libmseed` and `PhasePApy` folders where in modified state after that merge, as a result of that merge from develop. Does this not mean the change to the submodule versions came from develop?
> > > 
> > > 
> > > `libmseed` on `develop` still points to `c23cc3d` (October 2017). On this PR it somehow started pointing to `67f0bee` (June 2019). I'm not sure how this change could originate from `develop`.
> > 
> > 
> > Seems like a submodule can become weirdly detached after pull or merge, such as https://stackoverflow.com/a/36375256/5823205. I'll try to debug and roll back.
> 
> While we're at it, I just wanted to mention that it's happened before in another PR you merged some time ago, which updated the phasepapy submodule. I then had to go through the code to make sure nothing broke. Please keep an eye out to make sure submodules don't get inadvertently updated.
> I think something weird is happening in your dev environment; fortunately, I haven't experienced this in mine.

The update to PhasePApy was intentional, and we track a fork so it's a bit different from libmseed. In that case it is easy to very I only added a missing dependency to requirements.txt. If something breaks from such changes we should aim to make our unit testing pick it up.

**Comment by rh-downunder** [comment]
Please go ahead and merge; there's a lot to wade through in this PR and it looks like there's little overlap with existing functionality.

**Pull request merged**
